// @ts-nocheck
import type { Metadata } from "next";
import "./fonts.css";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Drawer from "@/lib/Drawer/Drawer";
import TopNav from "@/lib/TopNav/TopNav";
import ClientProviders from "@/lib/ClientProviders/ClientProviders";
import { ToastContainer, Bounce } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black antialiased overflow-hidden"
        style={{ fontFamily: 'var(--font-geist-sans)' }}
      >
        <ClientProviders />
        <TopNav />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <div className="main-container">
          <Drawer />
          <div className="main-body">{children}</div>
        </div>
      </body>
    </html>
  );
}
